name: global-proxy

x-defaults:
  network: &network
    networks:
      - dev-proxy-network # All dev containers must join this shared network

services:
  caddy:
    image: caddy:latest
    container_name: global-proxy-caddy
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3 support
      - "6006:6006"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
      - ./logs:/data/logs
      - caddy_data:/data
      - caddy_config:/config
    <<: *network
  log-prettifier:
    image: alpine
    container_name: log-prettifier
    volumes:
      - ./logs:/logs
    <<: *network
    entrypoint:
      - /bin/sh
      - -c
      - |
        apk add jq
        rm -f /logs/*.formatted.log
        for f in /logs/*.log; do
          tail -n +1 -f "$$f" | jq --unbuffered -R -r '
            fromjson? | select(.status != null) |
            "[\(.ts | floor | strftime("%H:%M:%S"))] [\(.level | ascii_upcase)] \(.status) \(.request.method) \(.request.host)\(.request.uri) [\(.request.client_ip)] (\((.duration * 1000) | floor)ms) \(.request.proto)"
          ' >> "$${f%.log}.formatted.log" &
        done
        wait


networks:
  dev-proxy-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
